/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module pattern_rom_15 (
    input [2:0] addressr,
    input [15:0] addressl,
    output reg [15:0] out
  );
  
  
  
  localparam A = 1152'h017f0004001b003f000701ef0155017d0004017f001b01ef003f0007017d0155001b017f0004003f000701ef017d0155017f0004001b003f000701ef0155017d001b017f017d000400070155003f01ef000401ef003f017f0007017d001b0155017f0004000701ef001b0155003f017d000401ef003f017f0007017d001b0155017f0004000701ef001b0155003f017d;
  
  always @* begin
    out = A[(addressr)*128+(addressl[0+2-:3])*16+15-:16];
  end
endmodule
