/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_11 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] s,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] sm;
  
  always @* begin
    sm = 16'h0000;
    
    case (alufn[0+0-:1])
      1'h0: begin
        sm = a + b;
      end
      1'h1: begin
        sm = a - b;
      end
      default: begin
        sm = a + b;
      end
    endcase
    n = sm[15+0-:1];
    z = ~(|sm);
    v = (a[15+0-:1] & (b[15+0-:1] ^ alufn[0+0-:1]) & !sm[15+0-:1]) | (!a[15+0-:1] & !(b[15+0-:1] ^ alufn[0+0-:1]) & sm[15+0-:1]);
    s = sm;
  end
endmodule
