/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [8-1:0] M_fsmc_seg;
  wire [4-1:0] M_fsmc_sel;
  wire [16-1:0] M_fsmc_out;
  reg [5-1:0] M_fsmc_iobutton;
  reg [16-1:0] M_fsmc_iodip;
  fsm_combine_1 fsmc (
    .clk(clk),
    .rst(rst),
    .iobutton(M_fsmc_iobutton),
    .iodip(M_fsmc_iodip),
    .seg(M_fsmc_seg),
    .sel(M_fsmc_sel),
    .out(M_fsmc_out)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_2 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    M_fsmc_iodip[0+7-:8] = io_dip[0+7-:8];
    M_fsmc_iodip[8+7-:8] = io_dip[8+7-:8];
    M_fsmc_iobutton = io_button;
    io_seg = M_fsmc_seg;
    io_sel = M_fsmc_sel;
    io_led[0+7-:8] = M_fsmc_out[0+7-:8];
    io_led[8+7-:8] = M_fsmc_out[8+7-:8];
  end
endmodule
