/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module find_neighbor_20 (
    input [15:0] c,
    output reg [15:0] s
  );
  
  
  
  always @* begin
    
    case (c[0+8-:9])
      9'h100: begin
        s = 16'h01a0;
      end
      9'h080: begin
        s = 16'h01d0;
      end
      9'h040: begin
        s = 16'h00c8;
      end
      9'h020: begin
        s = 16'h0134;
      end
      9'h010: begin
        s = 16'h00ba;
      end
      9'h008: begin
        s = 16'h0059;
      end
      9'h004: begin
        s = 16'h0026;
      end
      9'h002: begin
        s = 16'h0017;
      end
      9'h001: begin
        s = 16'h000b;
      end
      default: begin
        s = c;
      end
    endcase
  end
endmodule
