/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module flip_17 (
    input [15:0] c,
    input [15:0] current_state,
    output reg [15:0] s
  );
  
  
  
  reg [15:0] neighbor;
  
  wire [16-1:0] M_fn_s;
  reg [16-1:0] M_fn_c;
  find_neighbor_19 fn (
    .c(M_fn_c),
    .s(M_fn_s)
  );
  
  always @* begin
    M_fn_c = c;
    neighbor = M_fn_s;
    s = current_state ^ neighbor;
  end
endmodule
