/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_regfile_6 (
    input clk,
    input rst,
    input [15:0] wr_data,
    input [3:0] wrsel,
    input we,
    output reg [15:0] current_state,
    output reg [15:0] pattern,
    output reg [15:0] score,
    output reg [15:0] level
  );
  
  
  
  reg [15:0] M_state_store_d, M_state_store_q = 1'h0;
  reg [15:0] M_pattern_store_d, M_pattern_store_q = 1'h0;
  reg [15:0] M_score_store_d, M_score_store_q = 1'h0;
  reg [15:0] M_level_store_d, M_level_store_q = 1'h0;
  
  always @* begin
    M_state_store_d = M_state_store_q;
    M_score_store_d = M_score_store_q;
    M_pattern_store_d = M_pattern_store_q;
    M_level_store_d = M_level_store_q;
    
    if (we) begin
      
      case (wrsel)
        16'h0000: begin
          M_pattern_store_d = wr_data;
        end
        16'h0001: begin
          M_state_store_d = wr_data;
        end
        16'h0002: begin
          M_score_store_d = wr_data;
        end
        16'h0003: begin
          M_level_store_d = wr_data;
        end
      endcase
    end
    current_state = M_state_store_q;
    pattern = M_pattern_store_q;
    score = M_score_store_q;
    level = M_level_store_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_store_q <= 1'h0;
      M_pattern_store_q <= 1'h0;
      M_score_store_q <= 1'h0;
      M_level_store_q <= 1'h0;
    end else begin
      M_state_store_q <= M_state_store_d;
      M_pattern_store_q <= M_pattern_store_d;
      M_score_store_q <= M_score_store_d;
      M_level_store_q <= M_level_store_d;
    end
  end
  
endmodule
