/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module random_rom_18 (
    input [2:0] address,
    output reg [3:0] out
  );
  
  
  
  localparam NUM = 32'h12345678;
  
  always @* begin
    out = NUM[(address)*4+3-:4];
  end
endmodule
