/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module random_choose_9 (
    input clk,
    input rst,
    input button,
    output reg [3:0] out
  );
  
  
  
  wire [32-1:0] M_random_generate_num;
  reg [1-1:0] M_random_generate_next;
  pn_gen_17 random_generate (
    .clk(clk),
    .rst(rst),
    .seed(32'h00000100),
    .next(M_random_generate_next),
    .num(M_random_generate_num)
  );
  
  wire [4-1:0] M_choose_out;
  reg [3-1:0] M_choose_address;
  random_rom_18 choose (
    .address(M_choose_address),
    .out(M_choose_out)
  );
  
  reg [2:0] int;
  
  always @* begin
    M_random_generate_next = button;
    int = M_random_generate_num[0+2-:3];
    M_choose_address = int;
    out = M_choose_out;
  end
endmodule
