/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module rom_12 (
    input [4:0] address,
    output reg [15:0] outA,
    output reg [15:0] outB,
    output reg [5:0] alufn,
    output reg [2:0] outZVN,
    output reg [15:0] out
  );
  
  
  
  localparam A = 336'h0001000180007fff000f000f000fa5f0a5f0a5f00001007f800101000002f5aff5af8a0f055f8a0f0015;
  
  localparam B = 336'h000200027fff7fff000500050005f5aff5aff5af000300050003000001b71a15f5aff5af8a0f055f0580;
  
  localparam AL = 126'h0004101879661e5a0863fffcf3d75dc2;
  
  localparam ZVN = 66'h016c0000000000000;
  
  localparam O = 336'h0003ffff0001fffe0005000f000aa5a0f5ff505f00080003f00001a001a0000000010001000000017380;
  
  always @* begin
    outA = A[(address)*16+15-:16];
    outB = B[(address)*16+15-:16];
    alufn = AL[(address)*6+5-:6];
    outZVN = ZVN[(address)*3+2-:3];
    out = O[(address)*16+15-:16];
  end
endmodule
