/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shifter_16 (
    input [15:0] a,
    input [3:0] b,
    input [5:0] alufn,
    output reg [15:0] s
  );
  
  
  
  always @* begin
    
    case (alufn)
      6'h20: begin
        s = a << b;
      end
      6'h21: begin
        s = a >> b;
      end
      6'h23: begin
        s = $signed(a) >>> b;
      end
      default: begin
        s = a;
      end
    endcase
  end
endmodule
