/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module increase_score_16 (
    input clk,
    input rst,
    input reset,
    input increase,
    output reg [3:0] out
  );
  
  
  
  reg [3:0] M_digit1_d, M_digit1_q = 1'h0;
  
  always @* begin
    M_digit1_d = M_digit1_q;
    
    if (reset) begin
      M_digit1_d = 4'h0;
    end
    if (increase) begin
      if (M_digit1_q == 4'h9) begin
        M_digit1_d = 4'h0;
      end else begin
        M_digit1_d = M_digit1_q + 1'h1;
      end
    end
    out = M_digit1_q;
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_digit1_q <= 1'h0;
    end else begin
      M_digit1_q <= M_digit1_d;
    end
  end
  
endmodule
